import type { Block } from 'payload'

export const ReviewsBlock: Block = {
  slug: 'reviewsBlock',
  interfaceName: 'ReviewsBlockType',
  labels: {
    singular: 'Avis',
    plural: 'Avis',
  },
  fields: [
    {
      name: 'sectionSubtitle',
      type: 'text',
      required: true,
      localized: true,
      defaultValue: 'Témoignages',
      label: 'Sous-titre de section',
    },
    {
      name: 'sectionTitle',
      type: 'text',
      required: true,
      localized: true,
      defaultValue: 'Avis de nos Patients',
      label: 'Titre de section',
    },
    {
      name: 'reviews',
      type: 'array',
      label: 'Avis',
      minRows: 1,
      fields: [
        {
          name: 'name',
          type: 'text',
          required: true,
          label: 'Nom du patient',
        },
        {
          name: 'rating',
          type: 'number',
          required: true,
          min: 1,
          max: 5,
          defaultValue: 5,
          label: 'Note (1-5)',
        },
        {
          name: 'date',
          type: 'text',
          required: true,
          label: 'Date (ex: Janvier 2026)',
        },
        {
          name: 'text',
          type: 'textarea',
          required: true,
          localized: true,
          label: 'Témoignage',
        },
        {
          name: 'service',
          type: 'text',
          required: true,
          localized: true,
          label: 'Service concerné',
        },
      ],
      defaultValue: [
        {
          name: 'Ana Karité',
          rating: 5,
          date: 'Mai 2025',
          text: "J'ai connu Docteur Dounia avant qu'elle ait son cabinet et elle était déjà d'un très grand professionnalisme et d'excellents conseils. En tant que patient, elle nous explique en détails les pathologies ce qui est primordial. Son cabinet est un lieu très agréable qui permet de recevoir des soins en toute sérénité et confiance. Avoir une dermatologue comme Dr Dounia est précieux !",
          service: 'Dermatologie Médicale',
        },
        {
          name: 'Gabriel Faty',
          rating: 5,
          date: 'Fevrier 2026',
          text: "Excellente dermatologue, très professionnel et à l'écoute. Elle prend le temps d'expliquer les traitements et me merci vraiment en confiance. Je suis très satisfaite de mes consultations et je la recommande vivement.",
          service: 'Dermatologie Médicale',
        },
        {
          name: 'Aminata Kébé',
          rating: 5,
          date: 'Novembre 2025',
          text: 'Dr.Dounia El Akkaoui, une dermatologue douce attentive et très professionnelle. Elle a le sens de l’écoute et dotée d’une capacité innée à rassurer ses patients. Je suis très satisfaite de la prise en charge. Je vous le conseille vivement',
          service: 'Soins du visage',
        },
        {
          name: 'Faty',
          rating: 5,
          date: 'Juillet 2025',
          text: 'J’ai consulté le Dr Dounia EL AKKAOUI pour un problème d’acné, et je suis vraiment ravie de cette rencontre. Elle est très à l’écoute, douce et prend le temps de bien expliquer les choses. Ce que j’ai particulièrement apprécié, c’est qu’elle m’a proposé plusieurs options de traitement, avec un vrai suivi si le premier ne fonctionne pas. On se sent accompagnée et en confiance. Je vis en France mais je compte bien continuer les consultations avec elle à distance, car j’ai enfin trouvé une dermatologue qui me comprend. Je la recommande les yeux fermés !',
          service: 'Dermatologie Médicale',
        },
        {
          name: 'Chaimae Elyacoubi',
          rating: 5,
          date: 'Juillet 2025',
          text: "Je tiens a remercier chaleureusement dr Dounia pour son professionnalisme, son écoute et la qualité de ses soins. Elle a su me mettre en confiance dès la première consultation et a pris le temps de bien m'expliquer. Un grand merci merci pour votre dévouement.",
          service: 'Dermatologie Esthétique',
        },
        {
          name: 'Fatoumata BAH',
          rating: 5,
          date: 'Juin 2025',
          text: 'Je vous conseille docteur Dounia ,très professionnel elle vous explique en détail chaque processus selon votre traitement .Le respect des RV et un suivi après chaque séance ,moi perso elle m’a beaucoup aidé et grâce à elle aujourd’hui j’ai de plus plus en plus confiance en mon apparence merci à vous docteur que dieu vous bénisse 🙏',
          service: 'Soins',
        },
      ],
    },
    {
      name: 'ctaText',
      type: 'text',
      localized: true,
      defaultValue: 'Vous êtes patient(e) ? Partagez votre expérience avec nous.',
      label: 'Texte CTA',
    },
    {
      name: 'ctaLabel',
      type: 'text',
      localized: true,
      defaultValue: 'Laisser un avis',
      label: 'Texte bouton CTA',
    },
  ],
}
