import type { Block } from 'payload'

export const ContactBlock: Block = {
  slug: 'contactBlock',
  interfaceName: 'ContactBlockType',
  labels: {
    singular: 'Contact',
    plural: 'Contacts',
  },
  fields: [
    {
      name: 'sectionSubtitle',
      type: 'text',
      required: true,
      localized: true,
      defaultValue: 'Prenez rendez-vous',
      label: 'Sous-titre de section',
    },
    {
      name: 'sectionTitle',
      type: 'text',
      required: true,
      localized: true,
      defaultValue: 'Nous Contacter',
      label: 'Titre de section',
    },
    {
      name: 'address',
      type: 'textarea',
      required: true,
      defaultValue: 'Résidence Anna, 18 Rue de Kolda, Point E, Dakar, Sénégal',
      label: 'Adresse',
    },
    {
      name: 'phone',
      type: 'text',
      required: true,
      defaultValue: '+221 78 892 77 02',
      label: 'Téléphone principal',
    },
    {
      name: 'phone2',
      type: 'text',
      defaultValue: '+221 XX XXX XX XX',
      label: 'Téléphone secondaire',
    },
    {
      name: 'email',
      type: 'email',
      required: true,
      defaultValue: 'derma.douniaelakkaoui@gmail.com',
      label: 'Email',
    },
    {
      name: 'hours',
      type: 'text',
      required: true,
      localized: true,
      defaultValue: 'Lun - Sam : Sur rendez-vous',
      label: 'Horaires (ligne 1)',
    },
    {
      name: 'hours2',
      type: 'text',
      localized: true,
      defaultValue: 'Sam : 9h - 13h',
      label: 'Horaires (ligne 2)',
    },
    {
      name: 'ctaText',
      type: 'text',
      required: true,
      localized: true,
      defaultValue: 'Prenez soin de votre peau, prenez rendez-vous dès maintenant.',
      label: 'Texte CTA',
    },
    {
      name: 'ctaLabel',
      type: 'text',
      required: true,
      localized: true,
      defaultValue: 'Prendre Rendez-vous',
      label: 'Texte bouton CTA',
    },
    {
      name: 'ctaLink',
      type: 'text',
      required: true,
      defaultValue: 'tel:+221 78 892 77 02',
      label: 'Lien bouton CTA',
    },
    {
      name: 'mapEmbedUrl',
      type: 'text',
      required: true,
      defaultValue:
        'https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d3859.278799482938!2d-17.4604286!3d14.6968193!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0xec17327f180020b%3A0xe9ded1d954bbd3bb!2sDr%20Dounia%20EL%20AKKAOUI!5e0!3m2!1sfr!2ssn!4v1774561244282!5m2!1sfr!2ssn',
      label: 'URL Google Maps Embed',
    },
  ],
}
